### ISSUE TITLE
Documentation: What does your model do?

### ISSUE THREAD

**Issue by 3ygun** [tebesu/Tensorflow-Cpp-API-Training#1]
First, thank you for the post I'm trying similar things with the C++ API. However, when reading through the blog post it wasn't clear to me what the model actually does. Is it just adding 32 random numbers generated between 0 to 1 together?

**Comment by tebesu** [comment]
The model itself does not do anything useful. Its more a proof of concept. I made the blog post since I spent a large amount of time trying to get this to integrate with my C++ code. 

You could construct your own graph and load it with the C++ API. Although, the latest versions of tensorflow have changed and may have made this significantly easier than when I wrote the code (TensorFlow r0.8). Let me know if you have any other questions.

**Comment by 3ygun** [comment]
Thanks for the advice and help will do!
